### ISSUE TITLE
setting of "Extra key for trigger input method" always reverts to the default after session restart

### ISSUE THREAD

**Issue by gbuntu127** [fcitx/fcitx-configtool#10]
I changed "Extra key for trigger input method" to disabled using fcitx-configtool, it always reverted it back to the default "Shift Both" after restart current session. Following the suggestion from this [link](http://askubuntu.com/questions/752324/fcitx-extra-key-for-trigger-input-method-changes-back-to-default-after-restart)  does not help neither, the configuration "profile" file will revert to the default. Please suggestion a way of permanently change this setting. Thanks. 

Here are some related information:

```
$ inxi -S
   System:    Kernel: 4.4.0-31-generic x86_64 (64 bit) Desktop: Cinnamon 3.0.7
   Distro: Linux Mint 18 Sarah
```

```
$ fcitx --version
fcitx version: 4.2.9.1
```

**Comment by moudixtc** [comment]
Same problem here. Is there gonna be any progress on this issue?

**Comment by tcgriffith** [comment]
In my experience it's because of sogoupinyin instead of fcitx. I uninstalled it and completely saved my life. if this is the case I suggest you to have a try. [this blog](http://codepub.cn/2015/11/27/Ubuntu14-10-install-and-uninstall-sogou-input-method/) might help.

**Comment by wengxt** [comment]
I really have no idea what sogoupinyin is doing, because I'm not involved in the later sogou pinyin development. But I heard it really does some hacks with fcitx, so it is probably the case. Close it for now.

**Comment by hliu202** [comment]
I bypass this problem by setting it to `Super+Left Ctrl`.
