### ISSUE TITLE
CMake Error at CMakeLists.txt:6 (FIND_PACKAGE)

### ISSUE THREAD

**Issue by zoumi** [fcitx/fcitx-configtool#12]
cmake ..
    -- The C compiler identification is GNU 4.8.5
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found Gettext: /usr/bin/msgmerge (found version "0.18.2") 
    CMake Error at CMakeLists.txt:6 (FIND_PACKAGE):
      By not providing "FindFcitx.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "Fcitx", but
      CMake did not find one.

      Could not find a package configuration file provided by "Fcitx" (requested
      version 4.2.7) with any of the following names:

        FcitxConfig.cmake
        fcitx-config.cmake

      Add the installation prefix of "Fcitx" to CMAKE_PREFIX_PATH or set
      "Fcitx_DIR" to a directory containing one of the above files.  If "Fcitx"
      provides a separate development package or SDK, be sure it has been
      installed.

    -- Configuring incomplete, errors occurred!

It seemed that it was looking for FcitxConfig.cmake inside fcitx's source code.
Can I compile it without fcitx source code?

**Comment by yuyichao** [comment]
`FcitxConfig.cmake` should be installed.

**Comment by wengxt** [comment]
you need fcitx-libs-dev or sth with a similar name

**Comment by a8568730** [comment]
I stuck on make build too... I follow the advice above
```
sudo apt install fcitx-libs-dev
```
Then 
```
cmake ..
```
it worked.
