### ISSUE TITLE
cannot see list of IMs in gtk3 config tool

### ISSUE THREAD

**Issue by alick** [fcitx/fcitx-configtool#8]
When adding input methods using fcitx-config-gtk3, the list of input methods is always blank. However, fcitx-config-gtk (gtk2 tool) works fine.

OS: Fedora 22
GNOME: 3.16.2
fcitx-configtool: 0.4.7-4.fc22.x86_64

**Comment by alick** [comment]
![screenshot from 2015-09-29 14-12-29](https://cloud.githubusercontent.com/assets/933935/10175457/8da561a0-66b4-11e5-8196-00c7abe4f5f1.png)

**Comment by wengxt** [comment]
It should be already fixed in 0.4.8.
